<?php
session_start();

// ===========================================
// Step 1: Save customer address into session
// ===========================================
// The checkout form posts the customer’s address along with the payment request.
// We store it in PHP session so it can be displayed later on the success page.
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $_SESSION['address_name']    = $_POST['address_name'] ?? '';
    $_SESSION['address_street']  = $_POST['address_street'] ?? '';
    $_SESSION['address_city']    = $_POST['address_city'] ?? '';
    $_SESSION['address_state']   = $_POST['address_state'] ?? '';
    $_SESSION['address_zip']     = $_POST['address_zip'] ?? '';
    $_SESSION['address_country'] = $_POST['address_country'] ?? '';
}

// ===========================================
// Step 2: Load Stripe PHP SDK and configuration
// ===========================================
// The Stripe SDK provides classes and methods to connect to Stripe API.
// The config.php file contains our Stripe API keys.
require __DIR__ . '/../../stripe-php-17.6.0/init.php';
require_once __DIR__ . "/config.php";

// Set the secret key to authenticate requests with Stripe
\Stripe\Stripe::setApiKey(STRIPE_SECRET_KEY);

// ===========================================
// Step 3: Calculate the total order amount
// ===========================================
// Stripe expects the amount in cents (smallest currency unit).
// We loop through the shopping cart stored in session and sum up total.
$total = 0;
if (!empty($_SESSION['cart'])) {
    foreach ($_SESSION['cart'] as $item) {
        $total += $item['price'] * $item['qty'];
    }
}

// ===========================================
// Step 4: Create a Stripe Checkout Session
// ===========================================
// A checkout session generates a secure hosted payment page provided by Stripe.
// We pass line_items (products), currency, and order total in cents.
// success_url and cancel_url define where the customer is redirected after payment.
$checkout_session = \Stripe\Checkout\Session::create([
    'payment_method_types' => ['card'],
    'line_items' => [[
        'price_data' => [
            'currency' => 'aud',
            'product_data' => ['name' => 'Mini Shop Order'],
            'unit_amount' => $total * 100, // Stripe requires cents
        ],
        'quantity' => 1,
    ]],
    'mode' => 'payment',
    'success_url' => 'http://localhost/AS2/Payments/success.php?method=stripe&session_id={CHECKOUT_SESSION_ID}',
    'cancel_url' => 'http://localhost/AS2/Payments/Stripe/cancel.php',
]);

// ===========================================
// Step 5: Redirect customer to Stripe payment page
// ===========================================
// The customer is redirected to the hosted checkout page generated by Stripe.
// From here, the payment will be completed securely on Stripe’s servers.
header("Location: " . $checkout_session->url);
exit;
